# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-25 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('coating', models.CharField(max_length=20)),
                ('hardness', models.CharField(max_length=20)),
                ('net', models.IntegerField()),
                ('gross', models.IntegerField()),
                ('defective', models.BooleanField(default=False)),
            ],
        ),
    ]
