# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParadiseApp', '0002_auto_20180826_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('size', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.datetime(2018, 9, 5, 18, 23, 43, 161133))),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParadiseApp.Roll')),
            ],
        ),
    ]
