# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadiseApp', '0003_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='gross',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='net',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pack',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 19, 2, 27, 805095)),
        ),
    ]
