# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-06 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadiseApp', '0004_auto_20180905_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 19, 9, 12, 599768)),
        ),
    ]
